#
# Customized values for the Kong ingress controller, from the base file here
# https://github.com/Kong/charts/blob/main/charts/kong/values.yaml
#

image:
  repository: custom_kong
  tag: 2.8.1-alpine

proxy:
  enabled: true
  type: LoadBalancer

ingressController:
  enabled: true
  ingressClass: kong
  installCRDs: false

admin:
  enabled: false
  
  # This prevents lots of errors being reported in the kong proxy logs
  # https://github.com/Kong/kubernetes-ingress-controller/issues/2435
  tls:
    parameters: []

#
# Allow larger than the default 4KB headers to enable cookies containing AWS Cognito JWTs to be received
# Also enable the oauth-proxy plugin, which will be configured on SPA routes, to forwards JWTs to the API
#
env:
  database: 'off'
  nginx_proxy_proxy_buffer_size: '16k'
  nginx_proxy_proxy_buffers: '8 16k'
  nginx_proxy_large_client_header_buffers: '8 16k'
  plugins: 'bundled,oauth-proxy'