#
# Customized values for the Kong ingress controller, from the base file here
# https://github.com/Kong/charts/blob/main/charts/kong/values.yaml
#

image:
  repository: custom_kong
  tag: 2.8.1-alpine

proxy:
  enabled: true
  type: LoadBalancer

ingressController:
  enabled: true
  ingressClass: kong
  installCRDs: false

# The TLS setting prevents lots of errors being output in the kong proxy logs
# https://github.com/Kong/kubernetes-ingress-controller/issues/2435
admin:
  enabled: false
  tls:
    parameters: []

secretVolumes:
  - mycluster-com-tls

#
# Allow larger than the default 4KB headers to enable cookies containing AWS Cognito JWTs to be received
# Also enable the oauth-proxy plugin, which will be configured on SPA routes, to forward JWTs to the API
#
env:
  database: 'off'
  ssl_cert: '/etc/secrets/mycluster-com-tls/tls.crt'
  ssl_cert_key: '/etc/secrets/mycluster-com-tls/tls.key'
  nginx_proxy_proxy_buffer_size: '16k'
  nginx_proxy_proxy_buffers: '8 16k'
  nginx_proxy_large_client_header_buffers: '8 16k'
  plugins: 'bundled,oauth-proxy'
