#
# The Kubernetes resources for the Kibana UI
#
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: kibana-cert
spec:
  secretName: kibana-pkcs12
  issuerRef:
    name: ca-issuer
    kind: Issuer
  commonName: kibana-svc.default.svc
  dnsNames:
  - kibana-svc
  - kibana-svc.default.svc
  - kibana-svc.default.svc.cluster.local
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: kibana-pkcs12-password
        key: password
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.15.0
          env:
            - name: ELASTICSEARCH_HOSTS
              value: 'https://elasticsearch-svc:9200'
            - name: ELASTICSEARCH_USERNAME
              value: 'elastic'
            - name: ELASTICSEARCH_PASSWORD
              value: 'Password1'
            - name: SERVER_PUBLICBASEURL
              value: 'https://logs.mycompany.com'
            - name: SERVER_SSL_ENABLED
              value: 'true'
            - name: SERVER_SSL_KEYSTORE_PATH
              value: '/usr/share/kibana/config/certs/keystore.p12'
            - name: SERVER_SSL_KEYSTORE_PASSWORD
              value: 'Password1'
            - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
              value: '/usr/share/kibana/config/certs/ca.crt'
          ports:
          - containerPort: 5601
            name: kibana
          volumeMounts:
          - name: kibana-ssl-cert
            mountPath: /usr/share/kibana/config/certs
            readOnly: true
      volumes:
        - name: kibana-ssl-cert
          secret:
            secretName: kibana-pkcs12
---
kind: Service
apiVersion: v1
metadata:
  name: kibana-svc
spec:
  selector:
    app: kibana
  ports:
    - protocol: "TCP"
      port: 5601
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: kibana-ingress
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/secure-backends: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: 'HTTPS'
spec:
  tls:
    - hosts:
        - logs.mycompany.com
      secretName: mycompany-com-tls
  rules:
    - host: logs.mycompany.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana-svc
                port:
                  number: 5601