#
# The base configuration for a Kubernetes in Docker (KIND) development cluster
#
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # We can only run the ingress controller on a single node, so use the control plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
- role: worker
networking:
  # We use Calico for advanced networking capabilities
  disableDefaultCNI: true
  
  # Ensure that this matches the subnet configured for Docker
  podSubnet: 192.168.0.0/16